[package]
name = "slh-dsa"
description = """
Pure Rust implementation of SLH-DSA (aka SPHINCS+) as described in the
FIPS-205 standard
"""
version = "0.0.3"
edition = "2021"
rust-version = "1.73"
license = "Apache-2.0 OR MIT"
homepage = "https://github.com/RustCrypto/signatures/tree/master/slh-dsa"
repository = "https://github.com/RustCrypto/signatures"
readme = "README.md"
categories = ["cryptography"]
keywords = ["crypto", "signature"]
exclude = ["tests"]

[dependencies]
hybrid-array = { version = "0.2", features = ["extra-sizes"] }
typenum = { version = "1.17.0", features = ["const-generics"] }
sha3 = { version = "0.10", default-features = false }
zerocopy = { version = "0.7.34", features = ["derive"] }
rand_core = { version = "0.6" }
signature = { version = "2.2", default-features = false, features = ["rand_core"] }
hmac = "0.12"
sha2 = { version = "0.10", default-features = false }
digest = "0.10"
pkcs8 = { version = "0.10", default-features = false }
const-oid = { version = "0.9", features = ["db"] }
solana-program = { version = "2.3.0", default-features = false }          # ← 追加

[dev-dependencies]
hex-literal = "1"
hex = { version = "0.4.1", features = ["serde"] }
num-bigint = "0.4.4"
quickcheck = "1"
quickcheck_macros = "1"
proptest = "1.4.0"
criterion = "0.5"
aes = "0.8.0"
cipher = "0.4"
ctr = "0.9"
rand_core = "0.6"
paste = "1.0.15"
rand = "0.8"
serde_json = "1.0.124"
serde = { version = "1.0.207", features = ["derive"] }
pkcs8 = { version = "0.10", features = ["pem"] }

[lib]
bench = false

[[bench]]
name = "sign_verify"
harness = false

[features]
alloc   = []
default = ["alloc"]

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2"