[package]
name = "kem-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4.5", features = ["derive"] }
base64 = "0.21"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
pqcrypto-kyber = "0.8.1"
pqcrypto-traits = "0.3"
