name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  anchor-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Required Linux packages (per Solana docs)
      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            pkg-config \
            libudev-dev \
            llvm \
            libclang-dev \
            protobuf-compiler \
            libssl-dev

      # Quick install: Rust, Solana CLI, Anchor (no devnet usage; build only)
      - name: Install Solana toolchain (Rust + Solana CLI + Anchor)
        run: |
          curl --proto '=https' --tlsv1.2 -sSfL https://solana-install.solana.workers.dev | bash
          echo "$HOME/.local/share/solana/install/active_release/bin" >> "$GITHUB_PATH"
          echo "$HOME/.cargo/bin" >> "$GITHUB_PATH"

      # Verify tools are available
      - name: Show versions
        run: |
          rustc --version
          solana --version
          anchor --version

      # Build on-chain programs like local `anchor build`
      - name: Anchor build
        run: anchor build
