name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  anchor-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Use the Rust toolchain version documented in the repo
      - name: Install Rust (1.88.0)
        uses: dtolnay/rust-toolchain@1.88.0

      # Install Solana CLI (no network/devnet usage; build only)
      - name: Install Solana CLI
        run: |
          sh -c "$(curl -sSfL https://release.solana.com/v2.2.20/install)"
          echo "$HOME/.local/share/solana/install/active_release/bin" >> "$GITHUB_PATH"
          solana --version

      # Install Anchor CLI matching your repo
      - name: Install Anchor CLI
        run: |
          cargo install --locked --git https://github.com/coral-xyz/anchor --tag v0.31.1 anchor-cli
          anchor --version

      # Build on-chain programs (SBF/BPF) like local `anchor build`
      - name: Anchor build
        run: anchor build
