name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust (stable)
        uses: dtolnay/rust-toolchain@stable

      # Host-only build: no devnet/SBF; skip the wasm binding crate to keep CI minimal
      - name: Build (Rust workspace)
        run: cargo build --workspace --exclude slh-dsa-wasm --locked

      # Run a fast host-side unit test (no chain access)
      - name: Test (stark-prover)
        run: cargo test -p stark-prover --locked -- --nocapture
